### PR TITLE
fix: properly filter custom fields in GetCustomFields

### PR DESCRIPTION
**Pull request by thefirstofthe300**
When attempting to filter the returned custom fields in a resource
with the controller custom fields schema the proper field from the
resource was not being used.

### CODE REVIEW

**Comment by thefirstofthe300** [comment]
@pavel-z1 Can you take a look at this PR? It should [fix the behavior](https://github.com/lord-kyron/terraform-provider-phpipam/issues/31) I'm seeing in the dependent Terraform phpipam provider.

**Comment by pavel-z1** [comment]
Thank you @thefirstofthe300 
I will check PR.

**Comment by pavel-z1** [comment]
Hi @thefirstofthe300 
I have builded phpipam provider with your PR

But I steel don't receive custom_fields in the output.

I have simple terraform example:
```
data "phpipam_subnet" "datasubnet" {
  subnet_address = "192.168.1.0"
  subnet_mask    = 24
}

output "instance_ip_addr" {
  value = data.phpipam_subnet.datasubnet
}
```

Output:
```
instance_ip_addr = {
  "allow_ip_requests" = false
  "create_ptr_records" = false
  "description" = "Test subnet1"
  "display_hostnames" = false
  "edit_date" = "2020-12-03 22:08:43"
  "gateway" = {}
  "gateway_id" = ""
  "host_discovery_enabled" = false
  "id" = "28"
  "include_in_ping" = false
  "is_folder" = false
  "is_full" = false
  "linked_subnet_id" = 0
  "location_id" = 0
  "master_subnet_id" = 0
  "nameserver_id" = 0
  "permissions" = "{\"3\":\"1\",\"2\":\"2\"}"
  "scan_agent_id" = 0
  "section_id" = 1
  "show_name" = false
  "subnet_address" = "192.168.1.0"
  "subnet_id" = 28
  "subnet_mask" = 24
  "utilization_threshold" = 0
  "vlan_id" = 0
  "vrf_id" = 0
}
```

Can you pease provide your case, and how to test your changes?

**Comment by thefirstofthe300** [comment]
I have no idea if your code would return a custom field value because the subnet that you're pulling data from would need to have a custom field on it. The provider will return a null value for an empty custom_field value (as it should).

I have tested the code locally with my own PHPIPAM instance and it works as I'd expect.

If you run the following code, do you get any custom_fields?

```
resource "phpipam_section" "section" {
  name        = "tf-test"
  description = "Terraform test section"
}

resource "phpipam_subnet" "subnet" {
  section_id     = data.phpipam_section.section.section_id
  subnet_address = "<subnet_address>"
  subnet_mask    = <subnet_mask>

  custom_fields = {
    CustomTestSubnets = "terraform-test"
  }
}

data "phpipam_subnet" "subnetdata" {
  subnet_id = resource.phpipam_subnet.subnet.subnet_id
}

outputs "subnetdata" {
  value = data.phpipam_subnet.subnetdata.custom_fields
}
```

**Comment by pavel-z1** [comment]
Hi @thefirstofthe300 

**My software**
Terraform latest version:
```
# terraform --version
Terraform v0.14.7
```
PHPIPAM latest stable version:
```
git branch
  1.4
* 1.4.2
  master
```
PHPIPAM API configuration: `Nest custom fields` - No

**My test results**
Terraform configuration:
```
data "phpipam_section" "section" {
  name        = "Customers"
}

resource "phpipam_subnet" "subnet" {
  section_id     = data.phpipam_section.section.section_id
  subnet_address = "192.168.2.0"
  subnet_mask    = 24

  custom_fields = {
    custom_CustomTestSubnets = "terraform-test3"
  }
}

data "phpipam_subnet" "subnetdata" {
  subnet_id = phpipam_subnet.subnet.subnet_id
}

output "subnetdata" {
  value = data.phpipam_subnet.subnetdata
}
```

During execution receive crash when terraform try to create subnet:
```
# terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.phpipam_subnet.subnetdata will be read during apply
  # (config refers to values not yet known)
 <= data "phpipam_subnet" "subnetdata"  {
      + allow_ip_requests      = (known after apply)
      + create_ptr_records     = (known after apply)
      + custom_fields          = (known after apply)
      + description            = (known after apply)
      + display_hostnames      = (known after apply)
      + edit_date              = (known after apply)
      + gateway                = (known after apply)
      + gateway_id             = (known after apply)
      + host_discovery_enabled = (known after apply)
      + id                     = (known after apply)
      + include_in_ping        = (known after apply)
      + is_folder              = (known after apply)
      + is_full                = (known after apply)
      + linked_subnet_id       = (known after apply)
      + location_id            = (known after apply)
      + master_subnet_id       = (known after apply)
      + nameserver_id          = (known after apply)
      + parent_subnet_id       = (known after apply)
      + permissions            = (known after apply)
      + scan_agent_id          = (known after apply)
      + section_id             = (known after apply)
      + show_name              = (known after apply)
      + subnet_address         = (known after apply)
      + subnet_id              = (known after apply)
      + subnet_mask            = (known after apply)
      + utilization_threshold  = (known after apply)
      + vlan_id                = (known after apply)
      + vrf_id                 = (known after apply)
    }

  # phpipam_subnet.subnet will be created
  + resource "phpipam_subnet" "subnet" {
      + allow_ip_requests      = (known after apply)
      + create_ptr_records     = (known after apply)
      + custom_fields          = {
          + "custom_CustomTestSubnets" = "terraform-test3"
        }
      + description            = (known after apply)
      + display_hostnames      = (known after apply)
      + edit_date              = (known after apply)
      + gateway                = (known after apply)
      + gateway_id             = (known after apply)
      + host_discovery_enabled = (known after apply)
      + id                     = (known after apply)
      + include_in_ping        = (known after apply)
      + is_folder              = (known after apply)
      + is_full                = (known after apply)
      + linked_subnet_id       = (known after apply)
      + location_id            = (known after apply)
      + master_subnet_id       = (known after apply)
      + nameserver_id          = (known after apply)
      + parent_subnet_id       = (known after apply)
      + permissions            = (known after apply)
      + scan_agent_id          = (known after apply)
      + section_id             = 1
      + show_name              = (known after apply)
      + subnet_address         = "192.168.2.0"
      + subnet_id              = (known after apply)
      + subnet_mask            = 24
      + utilization_threshold  = (known after apply)
      + vlan_id                = (known after apply)
      + vrf_id                 = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + subnetdata = {
      + allow_ip_requests      = (known after apply)
      + create_ptr_records     = (known after apply)
      + custom_field_filter    = null
      + custom_fields          = (known after apply)
      + description            = (known after apply)
      + description_match      = null
      + display_hostnames      = (known after apply)
      + edit_date              = (known after apply)
      + gateway                = (known after apply)
      + gateway_id             = (known after apply)
      + host_discovery_enabled = (known after apply)
      + id                     = (known after apply)
      + include_in_ping        = (known after apply)
      + is_folder              = (known after apply)
      + is_full                = (known after apply)
      + linked_subnet_id       = (known after apply)
      + location_id            = (known after apply)
      + master_subnet_id       = (known after apply)
      + nameserver_id          = (known after apply)
      + parent_subnet_id       = (known after apply)
      + permissions            = (known after apply)
      + scan_agent_id          = (known after apply)
      + section_id             = (known after apply)
      + show_name              = (known after apply)
      + subnet_address         = (known after apply)
      + subnet_id              = (known after apply)
      + subnet_mask            = (known after apply)
      + utilization_threshold  = (known after apply)
      + vlan_id                = (known after apply)
      + vrf_id                 = (known after apply)
    }

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

phpipam_subnet.subnet: Creating...

Error: rpc error: code = Unavailable desc = transport is closing


panic: interface conversion: interface {} is nil, not map[string]interface {}
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam:
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: goroutine 36 [running]:
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: github.com/pavel-z1/phpipam-sdk-go/phpipam/client.(*Client).getCustomFieldsRequest(0xc0000108d8, 0x1c, 0x120ae5f, 0x7, 0xc0000af3e0, 0x0, 0x1089c80, 0xc0001bade0)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/terraform-providers/phpipam-sdk-go/phpipam/client/client.go:121 +0x3d1
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: github.com/pavel-z1/phpipam-sdk-go/phpipam/client.(*Client).GetCustomFields(0xc0000108d8, 0x1c, 0x120ae5f, 0x7, 0xc0001bade0, 0x1, 0x1)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/terraform-providers/phpipam-sdk-go/phpipam/client/client.go:109 +0x131
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: github.com/pavel-z1/phpipam-sdk-go/controllers/subnets.(*Controller).GetSubnetCustomFields(...)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/terraform-providers/phpipam-sdk-go/controllers/subnets/subnets.go:179
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: github.com/lord-kyron/terraform-provider-phpipam/plugin/providers/phpipam.dataSourcePHPIPAMSubnetRead(0xc000644700, 0xfe4220, 0xc0004e1660, 0x120ae5f, 0x7)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/terraform-providers/terraform-provider-phpipam/plugin/providers/phpipam/data_source_phpipam_subnet.go:49 +0x290
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: github.com/lord-kyron/terraform-provider-phpipam/plugin/providers/phpipam.resourcePHPIPAMSubnetCreate(0xc000644700, 0xfe4220, 0xc0004e1660, 0x2, 0x1aae8c0)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/terraform-providers/terraform-provider-phpipam/plugin/providers/phpipam/resource_phpipam_subnet.go:73 +0x232
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00008c480, 0xc000101ae0, 0xc000516c00, 0xfe4220, 0xc0004e1660, 0x1087a01, 0xc0001242c8, 0xc0002c9da0)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:310 +0x375
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000b8480, 0xc0005a7a38, 0xc000101ae0, 0xc000516c00, 0xc0002fabc8, 0xc00011e1f0, 0x1089c80)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/provider.go:294 +0x99
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000107e0, 0x13b9aa0, 0xc0002c8150, 0xc000644000, 0xc0000107e0, 0xc0002c8150, 0xc0002e1ba0)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:885 +0x8ab
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x11c4ca0, 0xc0000107e0, 0x13b9aa0, 0xc0002c8150, 0xc0005dc060, 0x0, 0x13b9aa0, 0xc0002c8150, 0xc000020800, 0x3ef)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000a2380, 0x13c4d20, 0xc000001c80, 0xc0003f4100, 0xc0006251a0, 0x1a6c320, 0x0, 0x0, 0x0)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1171 +0x522
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: google.golang.org/grpc.(*Server).handleStream(0xc0000a2380, 0x13c4d20, 0xc000001c80, 0xc0003f4100, 0x0)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:1494 +0xcc5
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00047e220, 0xc0000a2380, 0x13c4d20, 0xc000001c80, 0xc0003f4100)
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:834 +0xa5
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-03-05T11:10:36.960+0200 [DEBUG] plugin.terraform-provider-phpipam: 	/root/go/pkg/mod/google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd
2021-03-05T11:10:36.962+0200 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021/03/05 11:10:36 [DEBUG] phpipam_subnet.subnet: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/03/05 11:10:36 [TRACE] EvalMaybeTainted: phpipam_subnet.subnet encountered an error during creation, so it is now marked as tainted
2021/03/05 11:10:36 [TRACE] EvalWriteState: removing state object for phpipam_subnet.subnet
2021/03/05 11:10:36 [TRACE] EvalApplyProvisioners: phpipam_subnet.subnet has no state, so skipping provisioners
2021/03/05 11:10:36 [TRACE] EvalMaybeTainted: phpipam_subnet.subnet encountered an error during creation, so it is now marked as tainted
2021/03/05 11:10:36 [TRACE] EvalWriteState: removing state object for phpipam_subnet.subnet
2021/03/05 11:10:36 [TRACE] vertex "phpipam_subnet.subnet": visit complete
2021/03/05 11:10:36 [TRACE] dag/walk: upstream of "data.phpipam_subnet.subnetdata" errored, so skipping
2021/03/05 11:10:36 [TRACE] dag/walk: upstream of "provider[\"kwebbl.cloud/live/phpipam\"] (close)" errored, so skipping
2021/03/05 11:10:36 [TRACE] dag/walk: upstream of "output.subnetdata" errored, so skipping
2021/03/05 11:10:36 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/03/05 11:10:36 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/03/05 11:10:36 [TRACE] statemgr.Filesystem: not making a backup, because the new snapshot is identical to the old
2021/03/05 11:10:36 [TRACE] statemgr.Filesystem: no state changes since last snapshot
2021/03/05 11:10:36 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021-03-05T11:10:36.963+0200 [DEBUG] plugin: plugin process exited: path=.terraform/providers/kwebbl.cloud/live/phpipam/0.1.0/linux_amd64/terraform-provider-phpipam pid=27661 error="exit status 2"
2021/03/05 11:10:36 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/03/05 11:10:36 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-03-05T11:10:36.964+0200 [DEBUG] plugin: plugin exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

This is feature degradation. @thefirstofthe300  please check this, I can't merge this PR if it will broke feature for other SDK users.

-------------------------------------------------

**Behaviour with PHPIPAM API configuration: `Nest custom fields` - Yes**
Creation of subnet works without crash.
Created subnet receive custom field.

But data still not return information about custom fields:
```
# terraform apply
phpipam_subnet.subnet: Refreshing state... [id=27]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

subnetdata = {
  "allow_ip_requests" = false
  "create_ptr_records" = false
  "custom_field_filter" = tomap(null) /* of string */
  "custom_fields" = tomap(null) /* of string */
  "description" = ""
  "description_match" = tostring(null)
  "display_hostnames" = false
  "edit_date" = "2021-03-05 11:05:40"
  "gateway" = tomap({})
  "gateway_id" = ""
  "host_discovery_enabled" = false
  "id" = "27"
  "include_in_ping" = false
  "is_folder" = false
  "is_full" = false
  "linked_subnet_id" = 0
  "location_id" = 0
  "master_subnet_id" = 0
  "nameserver_id" = 0
  "parent_subnet_id" = tonumber(null)
  "permissions" = "{\"3\":\"1\",\"2\":\"2\"}"
  "scan_agent_id" = 0
  "section_id" = 1
  "show_name" = false
  "subnet_address" = "192.168.2.0"
  "subnet_id" = 27
  "subnet_mask" = 24
  "utilization_threshold" = 0
  "vlan_id" = 0
  "vrf_id" = 0
}
```

**Comment by lord-kyron** [comment]
@thefirstofthe300 - can you, please review this as it will be good to be fixed and merged.
Thanks!

**Comment by lord-kyron** [comment]
@pavel-z1 can you review and merge this?

**Comment by pavel-z1** [comment]
Hi @pavel-z1 
This PR was previously reviewed https://github.com/pavel-z1/phpipam-sdk-go/pull/4#issuecomment-791323064
PR cause error. I can't merge it. Need to fix first.

@thefirstofthe300 can you please review this PR once again?

**Comment by lord-kyron** [comment]
@pavel-z1
Can you please release a new version with the latest 1-2 merged fixes included so that I can update it in the terrafrom-provider?
Last release was 16 June 2022. 
Thanks!

**Comment by lord-kyron** [comment]
Closed because of 3 years of inactivity.

**Pull request closed without merging**
