### PR TITLE
Support for static authentication

### PR DESCRIPTION
**Pull request by meisterfischy**
Sets the password as the token, if the username is empty. This way one can login using an api token.

### CODE REVIEW

**Comment by lord-kyron** [comment]
@pavel-z1 I've checked and merged this.
Can you please, release a new version of the SDK? I will then build and release a new version fo the provider.

**Comment by NikitaCOEUR** [comment]
Hi,
@pavel-z1 can you try to build a new version of this sdk for @lord-kyron  ? 

Thanks for your work !

**Comment by lord-kyron** [comment]
@pavel-z1 I've checked and merged this.
Can you please, release a new version of the SDK? I will then build and release a new version fo the provider.

**Comment by pavel-z1** [comment]
Hi @lord-kyron 
The new release version vas created.

I've create PR to update sdk version inside terraform provide https://github.com/lord-kyron/terraform-provider-phpipam/pull/63

**Pull request merged**
